### ISSUE TITLE
service port is incorrect

### ISSUE THREAD

**Issue by maxisam** [aleveille/octant-dashboard-turnkey#1]
first of all, thanks for the awesome project

I think the port here is wrong. it should point to 8000 instead.

https://github.com/aleveille/octant-dashboard-turnkey/blob/ecfad2565356fec0428ca992bf6223e638fc7a17/helm/templates/ingress.yaml#L39

**Comment by aleveille** [comment]
Hi @maxisam,

Thansk for reporting this. It seems to work OK on my setup, are you having issues with this?

It's using the name of the service port (which is `http`, https://github.com/aleveille/octant-dashboard-turnkey/blob/master/helm/templates/service.yaml#L17)

Let me know if it's causing you issues. While I'm using it successfully, it might differ based on the API version.

**Comment by maxisam** [comment]
Interesting, I don't know if the name matters

https://github.com/aleveille/octant-dashboard-turnkey/blob/ecfad2565356fec0428ca992bf6223e638fc7a17/helm/templates/service.yaml#L10

And I think it is set by this, which is 8000

**Comment by aleveille** [comment]
I see. Yes I tend to use '8000' as the default port as my personal standard for ports in Kubernetes.

Would it make more sense to you if I used 8080 as the default port?
https://github.com/aleveille/octant-dashboard-turnkey/blob/ecfad2565356fec0428ca992bf6223e638fc7a17/helm/values.yaml#L35

**Comment by aleveille** [comment]
I'll be closing this issue. Feel free to reach out in the future!
