### ISSUE TITLE
Replace keycloak-gatekeeper with oauth2-proxy

### ISSUE THREAD

**Issue by fungiboletus** [aleveille/octant-dashboard-turnkey#16]
Hi,

[Keycloak-gatekeeper is discontinued and oauth2-proxy should be used instead.](https://www.keycloak.org/2020/08/sunsetting-louketo-project.adoc) The [docker image](https://hub.docker.com/r/keycloak/keycloak-gatekeeper) hasn't been updated since a few years.

I would like to update the helm chart to use `oauth2-proxy` instead. Probably using the [*official* project helm chart](https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy). There is also the [bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/oauth2-proxy/) that could be considered. Do you have a strong preference?

The deployment would look a bit different too, with another deployment and service for the oauth2-proxy instead of a side container in the octant pod. It's more complex but we can point the oauth2-proxy helm chart as a dependency when sso is enabled.

**Comment by aleveille** [comment]
Just as an update, this is still on my todo to work on your PRs & issues. It's been a busy few weeks on my end!

**Comment by fungiboletus** [comment]
No problem. I went ahead on my fork, and I think it works.

You can check the differences and the example in the readme there : https://github.com/SINTEF/octant-dashboard-turnkey

**Comment by aleveille** [comment]
@fungiboletus I was going to pull your changes into my repository, but I realized there's little values for us both to maintain nearly identical repository. If you are OK with this, I would deprecate my repository and redirect people to yours, making yours the primary repo for this chart from now on.

Let me know what you think.

**Comment by fungiboletus** [comment]
I wouldn't mind maintaining the repository instead of you if you don't want it anymore.

Another possibility is to add me to your repository as admin, where you could keep the ownership while having me pushing a few commits once in a while.

**Comment by aleveille** [comment]
Done :)

**Comment by fungiboletus** [comment]
Great! I was waiting for an update of octant before working on your repository again. Unfortunately it looks like octant is on standby for now.
