### ISSUE TITLE
Octant is dead

### ISSUE THREAD

**Issue by fungiboletus** [aleveille/octant-dashboard-turnkey#19]
VMWare has unfortunately stopped the development of Octant. [The main repository](https://github.com/vmware-archive/octant) is archived.

I stopped using octant and archived my fork. I will let you decide what to do on your repository. Thanks for your work 😊

**Comment by aleveille** [comment]
Thanks to you as well!  I appreciated your contributions and your fork, which allowed me to step into GH actions (something I've wanted to do for a long time, but never did!)
