### ISSUE TITLE
Web based Octant session isolation

### ISSUE THREAD

**Issue by arfiqbal** [aleveille/octant-dashboard-turnkey#5]
Hi

I have deployed the container and added multiple context so that i can switch between context
Everything works great and the web based octant working fine

Let assume we have 3 people in a team and we all are using the web based octant dashboard at the same time so the problem arise when someone change the context in his web browser it also change ours. so there is no session maintained here and we can't use at the same time

 Let me know if you have any query

**Comment by aleveille** [comment]
For this use case, I guess the best scenario would be for these people to run Octant locally. Octant is, as far as I know, not intended to serve multiple contexts/users at the same time.

We found Octant to be better than the default dashboard, but wanted to run it centrally in a read-only manner. This is what this repo does. Until Octant adds something like a "login" and a notion of session within their app, I'm afraid we just can't do what you are asking for.

Perhaps an Octant plugin could help (eg: with an auth proxy container providing JWT roles, a plugin could perhaps map that role to a context)

**Comment by arfiqbal** [comment]
@aleveille Thanks for your reply
i'm afraid that there is no such octant plugin...  i searched a lot but didn't find it
may be  you know that will help...

**Comment by aleveille** [comment]
@arfiqbal I'm afraid there's nothing I can do for you at the moment. If you ever hear of a plugin or an update that could help, please re-open an issue and I'll make sure to add support for the new feature/plugin.
