### ISSUE TITLE
Unable to deploy to internal load balancer

### ISSUE THREAD

**Issue by hectoralicea** [aleveille/octant-dashboard-turnkey#6]
In order to deploy using an internal load balancer you will need to add something like this to the service.yaml template

```
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
```
annotations for the service will be needed for either azure or aws load balancers so that internal (rather than internet) ips are generated.

**Comment by hectoralicea** [comment]
I was able to deploy the service to an internal load balancer by making the above changes.  Just wanted to use service, rather than an ingress.

**Comment by aleveille** [comment]
Hi @hectoralicea! Thanks for reporting, this is a really good suggestion and I'll make this improvement to the public chart shortly.

**Comment by aleveille** [comment]
Hi @hectoralicea,

This have been added to the chart version `0.16.1`.

Let me know if it works for you, or if you are OK to close this issue.

**Comment by aleveille** [comment]
I'll consider this issue resolved since we added support for this. Please reopen the issue if you feel that's not the case.
