### ISSUE TITLE
what do I add to myvalues.yaml to pull down and install the starboard-octant-plugin?

### ISSUE THREAD

**Issue by hectoralicea** [aleveille/octant-dashboard-turnkey#7]
What do I need to add to the myvalues.yaml in order for it to pull down and install the starboard-octant-plugin found here: 
https://github.com/aquasecurity/starboard-octant-plugin/releases/tag/v0.6.0

**Comment by hectoralicea** [comment]
So it looks like I may have to muck with the Dockerfile and copy the plugin into the docker build and use a local copy of my of the docker image, rather than the image from: aleveille/octant-dashboard:v0.16.1?

**Comment by aleveille** [comment]
Hi @hectoralicea, I'll see if I can build that kind of flexibility into the Docker image & the Helm chart values

**Comment by hectoralicea** [comment]
> Hi @hectoralicea, I'll see if I can build that kind of flexibility into the Docker image & the Helm chart values

Thanks.  Here's a good pattern to following. This works well in sonarqube.
https://github.com/Oteemo/charts/blob/cb878505ab57feb42ce059ff834a3f42c5d0b81f/charts/sonarqube/values.yaml#L134

**Comment by aleveille** [comment]
Hi @hectoralicea !

I've published a new release with this functionality. The chart version is `0.16.1`. You might have previously have installed version `1.0.x`. You'll notice that I've now aligned the chart version on Octant's version. While the backtracking the version number might be weird or (temporarily) annoying, I believe it'll be much easier to understand to have my chart version in sync with Octant's version.

Now for the actual issue at hand. I've added something very similar to what you shared. You can simply add a list of plugins in your values file under `plugins.install`.

```
plugins:
  install:
  - https://github.com/aquasecurity/starboard-octant-plugin/releases/download/v0.6.0/starboard-octant-plugin_linux_x86_64.tar.gz
  - https://github.com/bloodorangeio/octant-helm/releases/download/v0.1.0/octant-helm_0.1.0_linux_amd64.tar.gz
```

Limitations so far:
- I've noticed that the ability to load plugins is heavily impacted by the host's kernel. I was able to run this chart on Debian host with `5.4.65-1-pve` kernel, but Octant was giving mlock Go stacktrace on Ubuntu 20.04.1 LTS with `5.4.0-52-generic`. YMMV.
- Right now it can only extract .tar.gz archive. I tried using the flag to automatically decompress files based on their extensions, but that wasn't working so great.

All in all, what I've added is just an init container downloading the plugins. If you need even more flexibility, you could use `extraInitContainers` in your values file to do exactly what you need.

**Comment by aleveille** [comment]
I'll consider this issue resolved since we added support for this. Please reopen the issue if you feel that's not the case.
